### ISSUE TITLE
Session expiration not handle 

### ISSUE THREAD

**Issue by smadbe** [France-ioi/bebras-platform#11]
In the teacherInterface, when session is expired, requests know it (for instance receiving `{"success":false,"message":"Requ\u00eate invalide pour utilisateur non connect\u00e9"}`) but it is not reported in the UI while there is a `session_expired` string (don't know when it is raised). I think it is very unfortunate because teacher may easily leave a session open for one hour and then spend 30min to fix student names before realising that nothing is saved, loosing lots of time and hating us ;-)

**Comment by smadbe** [comment]
Is it possible that it still not work ? If I flush the session table, I can still interact with the UI which receives not-connected answer but does not notify me.

**Comment by eroux** [comment]
I'm affraid bugs are always a possibility... what action do you perform exactly?

**Comment by smadbe** [comment]
If I flush all the session table (dyndb) and I edit a contest.  Instead of `{"success":true,"recordID":"..."}`, I get a `Requête invalide pour utilisateur non connecté` but I would expect a message in the UI saying that I have to reconnect (not really for me but for coordinators in general).

**Comment by eroux** [comment]
Do you have the message in a popup or just in the result of the request?

**Comment by smadbe** [comment]
In the result of the request. And I think I should get it as a message in a popup.

**Comment by eroux** [comment]
ok, you should get a popup, can you give me an example of action that doesn't show a popup?

**Comment by smadbe** [comment]
Changing a contest name, refreshing the list of collaborators, deleting a student, ... 
Works on your side ?

**Comment by eroux** [comment]
I think this might be due to a difference in status header handling between versions of php, apache and nginx... can you please try again with latest commit?

**Comment by smadbe** [comment]
Now it shows "Requête invalide pour utilisateur non connecté", it is what's expected ?

**Comment by eroux** [comment]
indeed,thanks!
