### ISSUE TITLE
Halts with requests to: https://coordinateur.castor-informatique.fr/?v=1000000000 after install

### ISSUE THREAD

**Issue by hsluoyz** [France-ioi/bebras-platform#22]
I have finished the install. But opening: http://localhost/teacherInterface/index.php gives me blank:

![image](https://user-images.githubusercontent.com/3787410/64915647-3675b880-d79e-11e9-9da6-9e08875a8c4b.png)

There seems to be a lot of requests to: https://coordinateur.castor-informatique.fr/?v=1000000000  with no reply. I thought this repo is a local platform. Why does it still go to castor-informatique.fr ?

**Comment by FintanHinch** [comment]
Hi , just wondering did you solve this issue as I am having a similar problem . Thanks
