### ISSUE TITLE
Jstz - Bower not installing it properly

### ISSUE THREAD

**Issue by FintanHinch** [France-ioi/bebras-platform#38]
Hi,

I am having an issue while running bower install for teacherInterface. Jstz doesn't seem to install. Is there an updated link for this or any work arounds? I will include a screenshot of the errors I am getting. I would appreciate any sort of advice or help with this. 
Thanks.

![gitbebras](https://user-images.githubusercontent.com/83707904/221865872-5c97d1ad-0c20-4320-82bd-bccd779ecb17.png)
![gitbebras2](https://user-images.githubusercontent.com/83707904/221865879-1f765517-d741-4cab-a367-e3f1f9684486.png)

**Comment by FunnyPhantom** [comment]
Hey, I've fixed this by pointing the bower file to the equivalent github version and also updating the js file

**Comment by FunnyPhantom** [comment]
This is my bower version for teacherItnerface: 
```json
{
  "name": "teacherInterface",
  "version": "0.0.0",
  "homepage": "https://github.com/France-ioi/bebras-platform",
  "authors": [
    "France IOI"
  ],
  "license": "MIT",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "requirejs": "~2",
    "almond": "~0.3",
    "jquery": "~1.9",
    "jquery-ui": "~1.11",
    "pem-platform": "France-ioi/pem-platform",
    "i18next": "~1.10.2",
    "jqgrid": "5.0.1",
    "jQuery-ajaxTransport-XDomainRequest": "~1.0",
    "json3": "~3.3",
    "jquery-base64": "https://github.com/carlo/jquery-base64.git",
    "jstz": "https://raw.githubusercontent.com/pellepim/jstimezonedetect/0508acd36d5243a9215ee99ac2cb0d723c2fef4e/dist/jstz.min.js",
    "pdfmake": "^0.1.23"
  }
}
```

**Comment by FunnyPhantom** [comment]
Also I believe I did something that made both index.js and index.js.min to be generated. But dunno what. Maybe it was just changing the git url to download different versions :thinking: 
This is how my bower_components look like:
![image](https://github.com/France-ioi/bebras-platform/assets/25137956/6595953a-ce72-427b-98b2-d17ef439cf86)

**Comment by mblockelet** [comment]
Hello, the bower.json file has been updated, thank you for reporting that issue.
