### ISSUE TITLE
French sentences remaining in recover.php

### ISSUE THREAD

**Issue by smadbe** [France-ioi/bebras-platform#7]
(@eroux Mathias asked me to notify about this one so that you can fix it)

Few French sentences to be convert to translatable strings in `recover.php`:

` "Bonjour,\r\n\r\nPour définir un nouveau mot de passe, ouvrez le lien suivant dans votre navigateur  : \r\n\r\n".$link."\r\n\r\nN'hésitez pas à nous contacter si vous rencontrez des difficultés.\r\n\r\nCordialement,\r\n--\r\nL'équipe du Castor Informatique";`

  `   "Réinitialisation de mot de passe Coordinateur Castor Informatique";`

`"Le lien est invalide."`

**Comment by eroux** [comment]
fixed by https://github.com/France-ioi/bebras-platform/commit/0df7b36c2080d4c904651eccafbbd3a67734d85d
